# Generated by Django 4.0.3 on 2022-07-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
